# config/test_config.yaml
device:
  host: "192.168.88.171"
  port: 80
  username: "admin"
  password: "password"
  protocol: "http"  # или "https"

firmware:
  version_source: "config"                # Допустимые значения: "api" | "config"
  expected_version: "2025.05.175445501"

db_path: "resources/domophone.db"
http_timeout: 10